name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build API
      run: cargo build --verbose
    - name: Start Server, Run tests
      run: |
        cargo run &
        cargo test http_client -- --nocapture
